-- ============================================================================
-- llm-wiki-agent: PostgreSQL + pgvector schema
--
-- Usage:
--   psql -U wiki_user -d llm_wiki -f schema.sql
--
-- Requires:
--   CREATE EXTENSION IF NOT EXISTS vector;
--   CREATE EXTENSION IF NOT EXISTS zhparser;  -- optional, for CJK search
-- ============================================================================

BEGIN;

-- ═══════════════════════════════════════════════════════════════════════════
-- Extensions
-- ═══════════════════════════════════════════════════════════════════════════
CREATE EXTENSION IF NOT EXISTS vector;
-- zhparser is optional; if unavailable, set search.cjk_parser to 'bigram_app'
-- CREATE EXTENSION IF NOT EXISTS zhparser;


-- ═══════════════════════════════════════════════════════════════════════════
-- 1. wiki_pages — core content table with full-text search
-- ═══════════════════════════════════════════════════════════════════════════
CREATE TABLE wiki_pages (
    id              SERIAL PRIMARY KEY,
    path            TEXT UNIQUE NOT NULL,              -- 'wiki/sources/my-page.md'
    title           TEXT NOT NULL,
    page_type       TEXT NOT NULL DEFAULT 'source',    -- source/entity/concept/synthesis
    tags            TEXT[] DEFAULT '{}',
    body            TEXT NOT NULL,
    body_tsv        TSVECTOR,                          -- auto-generated by trigger
    quality_score   REAL DEFAULT 0,
    source_url      TEXT,
    source_type     TEXT,                               -- web/rss/arxiv/github
    extractor       TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT valid_page_type CHECK (page_type IN ('source','entity','concept','synthesis'))
);

-- FTS index: try zhparser first, fallback to simple with bigram application-level tokenization
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'zhparser') THEN
        CREATE TEXT SEARCH CONFIGURATION zh_cfg (PARSER = zhparser);
        ALTER TEXT SEARCH CONFIGURATION zh_cfg
            ADD MAPPING FOR n,v,a,i,e,l,j WITH simple;
        EXECUTE 'CREATE INDEX idx_wiki_fts ON wiki_pages USING GIN (body_tsv)';
    ELSE
        -- Fallback: use 'simple' config, application handles CJK bigram tokenization
        EXECUTE 'CREATE INDEX idx_wiki_fts ON wiki_pages USING GIN (body_tsv)';
    END IF;
END $$;

CREATE INDEX idx_wiki_type_time ON wiki_pages (page_type, updated_at DESC);
CREATE INDEX idx_wiki_source_url ON wiki_pages (source_url) WHERE source_url IS NOT NULL;
CREATE INDEX idx_wiki_tags ON wiki_pages USING GIN (tags);


-- ═══════════════════════════════════════════════════════════════════════════
-- 2. wiki_embeddings — vector embeddings (pgvector)
-- ═══════════════════════════════════════════════════════════════════════════
CREATE TABLE wiki_embeddings (
    id              SERIAL PRIMARY KEY,
    page_path       TEXT UNIQUE NOT NULL REFERENCES wiki_pages(path) ON DELETE CASCADE,
    embedding       HALFVEC(768),          -- nomic-embed-text = 768 dims, halfvec saves 50% space
    model           TEXT NOT NULL DEFAULT 'nomic-embed-text',
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- HNSW index: faster queries than IVFFlat, suitable for <100k vectors
CREATE INDEX idx_wiki_embedding ON wiki_embeddings
    USING hnsw (embedding halfvec_cosine_ops)
    WITH (m = 16, ef_construction = 200);


-- ═══════════════════════════════════════════════════════════════════════════
-- 3. pipeline_state — replaces raw-inbox/state.json
-- ═══════════════════════════════════════════════════════════════════════════
CREATE TABLE pipeline_state (
    url             TEXT PRIMARY KEY,
    etag            TEXT,
    last_modified   TEXT,
    content_hash    TEXT,
    fetched_at      TIMESTAMPTZ,
    ingested_at     TIMESTAMPTZ,
    source_type     TEXT,                              -- web/rss/arxiv/github
    status          TEXT DEFAULT 'pending',            -- pending/fetched/ingested/failed/skipped
    error_message   TEXT,
    retry_count     INT DEFAULT 0,
    next_retry_at   TIMESTAMPTZ
);

CREATE INDEX idx_pipeline_status ON pipeline_state (status, next_retry_at);
CREATE INDEX idx_pipeline_hash ON pipeline_state (content_hash);
CREATE INDEX idx_pipeline_source ON pipeline_state (source_type, fetched_at DESC);


-- ═══════════════════════════════════════════════════════════════════════════
-- 4. scheduler_jobs — replaces state/scheduler_metrics.db
-- ═══════════════════════════════════════════════════════════════════════════
CREATE TABLE scheduler_jobs (
    id              SERIAL PRIMARY KEY,
    job_name        TEXT NOT NULL,
    started_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at     TIMESTAMPTZ,
    status          TEXT DEFAULT 'running',            -- running/success/failure
    duration_ms     REAL,
    items_count     INT DEFAULT 0,
    error_msg       TEXT
);

CREATE INDEX idx_jobs_name_time ON scheduler_jobs (job_name, started_at DESC);
CREATE INDEX idx_jobs_status ON scheduler_jobs (status);


-- ═══════════════════════════════════════════════════════════════════════════
-- 5. search_analytics — replaces state/search_analytics.db
-- ═══════════════════════════════════════════════════════════════════════════
CREATE TABLE search_queries (
    id              SERIAL PRIMARY KEY,
    timestamp       TIMESTAMPTZ DEFAULT NOW(),
    query           TEXT NOT NULL,
    result_count    INT DEFAULT 0,
    source          TEXT DEFAULT 'fts',                -- fts/hybrid/semantic
    latency_ms      REAL,
    did_you_mean    TEXT
);

CREATE INDEX idx_search_time ON search_queries (timestamp DESC);
CREATE INDEX idx_search_zero ON search_queries (timestamp DESC) WHERE result_count = 0;


-- ═══════════════════════════════════════════════════════════════════════════
-- 6. Auxiliary tables (domain strategies, fingerprints, refresh monitor)
-- ═══════════════════════════════════════════════════════════════════════════

-- Domain extraction strategy learning
CREATE TABLE domain_strategies (
    domain                  TEXT PRIMARY KEY,
    best_engine             TEXT,
    success_count           INT DEFAULT 0,
    failure_count           INT DEFAULT 0,
    avg_quality             REAL DEFAULT 0,
    fast_path               BOOLEAN DEFAULT FALSE,
    consecutive_successes   INT DEFAULT 0,
    updated_at              TIMESTAMPTZ DEFAULT NOW()
);

-- Content fingerprint deduplication
CREATE TABLE content_fingerprints (
    hash            TEXT PRIMARY KEY,
    first_url       TEXT NOT NULL,
    seen_count      INT DEFAULT 1,
    first_seen      TIMESTAMPTZ DEFAULT NOW(),
    last_seen       TIMESTAMPTZ DEFAULT NOW()
);

-- Refresh monitor cache
CREATE TABLE refresh_monitor (
    source_url          TEXT PRIMARY KEY,
    last_checked_at     TIMESTAMPTZ,
    total_changes       INT DEFAULT 0,
    last_change_at      TIMESTAMPTZ,
    checks_count        INT DEFAULT 0,
    avg_days_between    REAL,
    change_timestamps   JSONB DEFAULT '[]'
);


-- ═══════════════════════════════════════════════════════════════════════════
-- Triggers
-- ═══════════════════════════════════════════════════════════════════════════

-- Auto-update body_tsv on INSERT/UPDATE
CREATE OR REPLACE FUNCTION wiki_tsv_trigger() RETURNS trigger AS $$
DECLARE
    cfg_name TEXT;
BEGIN
    -- Allow callers to supply their own body_tsv (e.g. CJK bigram fallback)
    IF NEW.body_tsv IS NOT NULL THEN
        RETURN NEW;
    END IF;

    -- Check if zhparser config exists
    IF EXISTS (SELECT 1 FROM pg_ts_config WHERE cfgname = 'zh_cfg') THEN
        cfg_name := 'zh_cfg';
    ELSE
        cfg_name := 'simple';
    END IF;
    NEW.body_tsv := to_tsvector(cfg_name, coalesce(NEW.title, '') || ' ' || coalesce(NEW.body, ''));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS wiki_tsv_update ON wiki_pages;
CREATE TRIGGER wiki_tsv_update
    BEFORE INSERT OR UPDATE ON wiki_pages
    FOR EACH ROW EXECUTE FUNCTION wiki_tsv_trigger();

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_timestamp() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS wiki_pages_updated ON wiki_pages;
CREATE TRIGGER wiki_pages_updated
    BEFORE UPDATE ON wiki_pages
    FOR EACH ROW EXECUTE FUNCTION update_timestamp();

DROP TRIGGER IF EXISTS wiki_embeddings_updated ON wiki_embeddings;
CREATE TRIGGER wiki_embeddings_updated
    BEFORE UPDATE ON wiki_embeddings
    FOR EACH ROW EXECUTE FUNCTION update_timestamp();


-- ═══════════════════════════════════════════════════════════════════════════
-- Hybrid search function
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION hybrid_search(
    query_text      TEXT,
    query_embedding HALFVEC,
    result_limit    INT DEFAULT 20,
    fts_weight      REAL DEFAULT 0.6,
    vec_weight      REAL DEFAULT 0.4
) RETURNS TABLE (
    path            TEXT,
    title           TEXT,
    page_type       TEXT,
    excerpt         TEXT,
    hybrid_score    REAL,
    updated_at      TIMESTAMPTZ
) AS $$
DECLARE
    ts_config TEXT;
BEGIN
    IF EXISTS (SELECT 1 FROM pg_ts_config WHERE cfgname = 'zh_cfg') THEN
        ts_config := 'zh_cfg';
    ELSE
        ts_config := 'simple';
    END IF;

    RETURN QUERY
    WITH fts_results AS (
        SELECT
            wp.path,
            wp.title,
            wp.page_type,
            ts_rank(wp.body_tsv, websearch_to_tsquery(ts_config, query_text)) AS fts_rank,
            LEFT(wp.body, 300) AS body_excerpt,
            wp.updated_at
        FROM wiki_pages wp
        WHERE wp.body_tsv @@ websearch_to_tsquery(ts_config, query_text)
        LIMIT result_limit * 3
    ),
    vec_results AS (
        SELECT
            we.page_path,
            1 - (we.embedding <=> query_embedding) AS vec_score
        FROM wiki_embeddings we
        WHERE we.embedding IS NOT NULL
        ORDER BY we.embedding <=> query_embedding
        LIMIT result_limit * 3
    )
    SELECT
        COALESCE(f.path, v.page_path) AS path,
        COALESCE(f.title, '') AS title,
        COALESCE(f.page_type, 'unknown') AS page_type,
        COALESCE(f.body_excerpt, '') AS excerpt,
        (fts_weight * COALESCE(f.fts_rank, 0) + vec_weight * COALESCE(v.vec_score, 0)) AS hybrid_score,
        f.updated_at
    FROM fts_results f
    FULL OUTER JOIN vec_results v ON f.path = v.page_path
    ORDER BY hybrid_score DESC
    LIMIT result_limit;
END;
$$ LANGUAGE plpgsql STABLE;


-- ═══════════════════════════════════════════════════════════════════════════
-- 7. Jarvis agent system tables
-- ═══════════════════════════════════════════════════════════════════════════

-- Event bus
CREATE TABLE jarvis_events (
    id              TEXT PRIMARY KEY,
    name            TEXT NOT NULL,
    category        TEXT NOT NULL,
    payload_json    JSONB,
    timestamp       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source          TEXT NOT NULL DEFAULT ''
);

CREATE INDEX idx_jarvis_events_time ON jarvis_events (timestamp DESC);
CREATE INDEX idx_jarvis_events_cat ON jarvis_events (category, timestamp DESC);

-- Approval queue
CREATE TABLE jarvis_approvals (
    id              TEXT PRIMARY KEY,
    step_json       JSONB NOT NULL,
    reason          TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'pending',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at     TIMESTAMPTZ,
    resolved_by     TEXT,
    auto_approved   BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_jarvis_approvals_status ON jarvis_approvals (status, created_at DESC);

-- Goals
CREATE TABLE jarvis_goals (
    id              TEXT PRIMARY KEY,
    title           TEXT NOT NULL,
    description     TEXT NOT NULL DEFAULT '',
    status          TEXT NOT NULL DEFAULT 'pending',
    priority        TEXT NOT NULL DEFAULT 'medium',
    progress        REAL NOT NULL DEFAULT 0.0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deadline        TEXT NOT NULL DEFAULT '',
    parent_goal_id  TEXT NOT NULL DEFAULT '',
    metrics_json    JSONB NOT NULL DEFAULT '{}'
);

CREATE INDEX idx_jarvis_goals_status ON jarvis_goals (status, created_at DESC);

-- Learner lessons
CREATE TABLE jarvis_lessons (
    id              TEXT PRIMARY KEY,
    category        TEXT NOT NULL,
    pattern         TEXT NOT NULL,
    action          TEXT NOT NULL,
    confidence      REAL NOT NULL DEFAULT 0.5,
    learned_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source          TEXT NOT NULL DEFAULT '',
    applied_count   INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_jarvis_lessons_cat ON jarvis_lessons (category, learned_at DESC);

-- Multi-agent
CREATE TABLE jarvis_agents (
    id              TEXT PRIMARY KEY,
    name            TEXT NOT NULL,
    role            TEXT NOT NULL,
    description     TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'idle',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_active     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    tasks_completed INTEGER NOT NULL DEFAULT 0,
    tasks_failed    INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE jarvis_tasks (
    id              TEXT PRIMARY KEY,
    agent_id        TEXT NOT NULL REFERENCES jarvis_agents(id) ON DELETE CASCADE,
    task            TEXT NOT NULL,
    priority        TEXT NOT NULL DEFAULT 'medium',
    status          TEXT NOT NULL DEFAULT 'pending',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at    TIMESTAMPTZ,
    result_json     JSONB
);

CREATE INDEX idx_jarvis_tasks_agent ON jarvis_tasks (agent_id, status);

-- Plugin market
CREATE TABLE jarvis_plugins (
    id              TEXT PRIMARY KEY,
    name            TEXT NOT NULL,
    version         TEXT NOT NULL,
    description     TEXT NOT NULL,
    author          TEXT NOT NULL,
    category        TEXT NOT NULL,
    tool_count      INTEGER NOT NULL DEFAULT 0,
    risk_level      TEXT NOT NULL DEFAULT 'L1',
    source_url      TEXT NOT NULL DEFAULT '',
    installed       BOOLEAN NOT NULL DEFAULT FALSE,
    installed_at    TIMESTAMPTZ
);

-- Scheduled tasks
CREATE TABLE jarvis_scheduled_tasks (
    id              TEXT PRIMARY KEY,
    task_type       TEXT NOT NULL,
    payload_json    JSONB,
    scheduled_at    TIMESTAMPTZ NOT NULL,
    status          TEXT NOT NULL DEFAULT 'pending',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at    TIMESTAMPTZ,
    result_json     JSONB
);

CREATE INDEX idx_jarvis_sched_time ON jarvis_scheduled_tasks (scheduled_at, status);


COMMIT;
