#!/usr/bin/env python3
"""Graphify Git hooks — auto-rebuild knowledge graph on git events.

Usage:
    python tools/graphify_hooks.py install    # install hooks into .git/hooks
    python tools/graphify_hooks.py uninstall  # remove hooks
    python tools/graphify_hooks.py status     # show hook status
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).parent.parent
HOOKS_DIR = REPO / ".git" / "hooks"
GRAPHIFY_HOOKS = {"post-commit", "post-checkout", "post-merge"}

HOOK_SCRIPT = '''#!/bin/sh
# Auto-generated by graphify_hooks.py — do not edit manually
# Rebuild knowledge graph after git events

GRAPHIFY_PY="{repo}/tools/build_graph.py"

echo "[graphify] Rebuilding knowledge graph..."
python "$GRAPHIFY_PY" --code --no-infer 2>/dev/null || python3 "$GRAPHIFY_PY" --code --no-infer 2>/dev/null || true
'''.format(repo=str(REPO).replace("\\", "/"))


def install() -> None:
    if not HOOKS_DIR.exists():
        print("Error: .git/hooks not found. Are you in a git repository?")
        sys.exit(1)

    for name in GRAPHIFY_HOOKS:
        hook_path = HOOKS_DIR / name
        if hook_path.exists():
            content = hook_path.read_text(encoding="utf-8")
            if "graphify" in content:
                print(f"  {name}: already installed (skip)")
                continue
            # Append to existing hook
            with hook_path.open("a", encoding="utf-8") as f:
                f.write("\n" + HOOK_SCRIPT)
            print(f"  {name}: appended to existing hook")
        else:
            hook_path.write_text(HOOK_SCRIPT, encoding="utf-8")
            hook_path.chmod(0o755)
            print(f"  {name}: installed")

    print("Done. Graph will rebuild on commit / checkout / merge.")


def uninstall() -> None:
    if not HOOKS_DIR.exists():
        print("Error: .git/hooks not found.")
        sys.exit(1)

    for name in GRAPHIFY_HOOKS:
        hook_path = HOOKS_DIR / name
        if not hook_path.exists():
            print(f"  {name}: not found (skip)")
            continue
        content = hook_path.read_text(encoding="utf-8")
        if "graphify" not in content:
            print(f"  {name}: no graphify marker (skip)")
            continue
        # If the hook is ONLY our script, delete it
        lines = content.splitlines()
        is_only_ours = all("graphify" in line or line.strip().startswith("#") or not line.strip() for line in lines)
        if is_only_ours:
            hook_path.unlink()
            print(f"  {name}: removed")
        else:
            # Remove graphify block
            new_lines = []
            in_block = False
            for line in lines:
                if "graphify" in line.lower() and "# Auto-generated" in line:
                    in_block = True
                if in_block and line.strip() == "":
                    in_block = False
                    continue
                if not in_block:
                    new_lines.append(line)
            hook_path.write_text("\n".join(new_lines).rstrip() + "\n", encoding="utf-8")
            print(f"  {name}: cleaned")

    print("Done. Graphify hooks removed.")


def status() -> None:
    if not HOOKS_DIR.exists():
        print("Error: .git/hooks not found.")
        sys.exit(1)

    print("Graphify hook status:")
    for name in GRAPHIFY_HOOKS:
        hook_path = HOOKS_DIR / name
        if not hook_path.exists():
            print(f"  {name}: not installed")
        elif "graphify" in hook_path.read_text(encoding="utf-8"):
            print(f"  {name}: installed")
        else:
            print(f"  {name}: exists (no graphify)")


def main() -> None:
    parser = argparse.ArgumentParser(description="Manage Graphify git hooks")
    parser.add_argument("command", choices=["install", "uninstall", "status"], help="Action to perform")
    args = parser.parse_args()

    if args.command == "install":
        install()
    elif args.command == "uninstall":
        uninstall()
    elif args.command == "status":
        status()


if __name__ == "__main__":
    main()
